name: k1s0_serviceauth
description: Service-to-service authentication library for k1s0 platform
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
