app:
  name: config-server
  version: "0.1.0"
  environment: development
  tier: system

server:
  port: 8082
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 5s

grpc:
  port: 50053

database:
  host: localhost
  port: 5432
  user: dev
  password: dev
  dbname: k1s0_system
  sslmode: disable

kafka:
  brokers:
    - "localhost:9092"
  topics:
    publish: "k1s0.system.config.changed.v1"
    subscribe: "k1s0.system.config.changed.v1"
