app:
  name: config-server
  version: "0.1.0"
  environment: production
  tier: system

server:
  port: 8082
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 30s

grpc:
  port: 50053

database:
  host: localhost
  port: 5432
  user: postgres
  password: ""
  dbname: config
  sslmode: require

kafka:
  brokers:
    - "localhost:9092"
  topics:
    publish: "k1s0.system.config.changed.v1"
    subscribe: "k1s0.system.config.changed.v1"
