apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app.kubernetes.io/name: {{ include "auth-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    app:
      name: k1s0-auth-server
      version: {{ .Chart.AppVersion | quote }}
      environment: {{ .Values.env.ENVIRONMENT | default "production" | quote }}
    server:
      host: "0.0.0.0"
      port: {{ .Values.service.httpPort }}
    auth:
      jwks:
        url: ""
        cache_ttl_secs: 3600
      jwt:
        issuer: ""
        audience: ""
