app:
  name: "k1s0-config-server"
  version: "0.1.0"
  environment: "prod"

server:
  host: "0.0.0.0"
  port: 8082

database:
  host: "postgres.k1s0-system.svc.cluster.local"
  port: 5432
  name: "k1s0_config"
  user: "app"
  password: ""
  ssl_mode: "require"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

kafka:
  brokers:
    - "kafka-0.messaging.svc.cluster.local:9092"
    - "kafka-1.messaging.svc.cluster.local:9092"
    - "kafka-2.messaging.svc.cluster.local:9092"
  consumer_group: "config-server.default"
  security_protocol: "SASL_SSL"
  sasl:
    mechanism: "SCRAM-SHA-512"
    username: ""
    password: ""
  topics:
    publish:
      - "k1s0.system.config.changed.v1"
    subscribe: []
