app:
  environment: "production"

server:
  read_timeout: "10s"
  write_timeout: "10s"

database:
  ssl_mode: "verify-full"
  max_open_conns: 50
  max_idle_conns: 10

kafka:
  brokers:
    - "kafka-0.messaging.svc.cluster.local:9093"
    - "kafka-1.messaging.svc.cluster.local:9093"
    - "kafka-2.messaging.svc.cluster.local:9093"
  security_protocol: "SASL_SSL"
  sasl:
    mechanism: "SCRAM-SHA-512"
    username: ""                   # Vault から注入
    password: ""                   # Vault から注入
  tls:
    ca_cert_path: "/etc/kafka/certs/ca.crt"

observability:
  log:
    level: "warn"
  trace:
    sample_rate: 0.1
