name: k1s0_migration
description: Migration library for k1s0 platform
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  path: ^1.9.0
  meta: ^1.14.0
  postgres: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
