replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

pdb:
  enabled: false

vault:
  enabled: false

config:
  data:
    config.yaml: |
      app:
        environment: dev
      graphql:
        introspection: true
        playground: true
      backends:
        tenant:
          address: "http://tenant.k1s0-system.svc.cluster.local:50051"
        featureflag:
          address: "http://featureflag.k1s0-system.svc.cluster.local:50051"
        config:
          address: "http://config.k1s0-system.svc.cluster.local:50051"
      observability:
        log:
          level: debug
          format: text
        trace:
          sample_rate: 1.0
