# k1s0-admin ClusterRoleBinding - インフラチーム
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k1s0-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k1s0-admin
subjects:
  - kind: Group
    name: k1s0-admin
    apiGroup: rbac.authorization.k8s.io
---
# k1s0-operator ClusterRoleBinding - 運用チーム
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k1s0-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k1s0-operator
subjects:
  - kind: Group
    name: k1s0-operator
    apiGroup: rbac.authorization.k8s.io
---
# k1s0-developer ClusterRoleBinding - 開発者
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k1s0-developer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k1s0-developer
subjects:
  - kind: Group
    name: k1s0-developer
    apiGroup: rbac.authorization.k8s.io
---
# readonly ClusterRoleBinding - 運用監視
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonly
subjects:
  - kind: Group
    name: readonly
    apiGroup: rbac.authorization.k8s.io
